CREATE TABLE IF NOT EXISTS FARMACIA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    localidad VARCHAR(100) NOT NULL,
    cuil VARCHAR(100) NOT NULL,
    calle VARCHAR(100) NOT NULL,
    nro_calle VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    farmacia_id BIGINT NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    precio DECIMAL(10,4) NOT NULL,
    CONSTRAINT fk_farmacia FOREIGN KEY (farmacia_id) REFERENCES FARMACIA(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VACUNA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cant_aplicaciones INT NOT NULL,
    CONSTRAINT fk_producto_vacuna FOREIGN KEY (id) REFERENCES PRODUCTO(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MEDICAMENTO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo VARCHAR(100) NOT NULL,
    dosis DECIMAL(10,4) NOT NULL,
    CONSTRAINT fk_producto_medicamento FOREIGN KEY (id) REFERENCES PRODUCTO(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HIGIENE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    aroma VARCHAR(50) NOT NULL,
    hipoalergenico BOOLEAN NOT NULL,
    CONSTRAINT fk_producto_higiene FOREIGN KEY (id) REFERENCES PRODUCTO(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    permiso VARCHAR(100) NOT NULL
);

